export const mockmealCategories = {
  meals: [
    { strCategory: 'Beef' },
    { strCategory: 'Breakfast' },
    { strCategory: 'Chicken' },
    { strCategory: 'Dessert' },
    { strCategory: 'Goat' },
    { strCategory: 'Lamb' },
    { strCategory: 'Miscellaneous' },
    { strCategory: 'Pasta' },
    { strCategory: 'Pork' },
    { strCategory: 'Seafood' },
    { strCategory: 'Side' },
    { strCategory: 'Starter' },
    { strCategory: 'Vegan' },
    { strCategory: 'Vegetarian' },
  ],
};

export const mockdrinkCategories = {
  drinks: [
    { strCategory: 'Ordinary Drink' },
    { strCategory: 'Cocktail' },
    { strCategory: 'Shake' },
    { strCategory: 'Other/Unknown' },
    { strCategory: 'Cocoa' },
    { strCategory: 'Shot' },
    { strCategory: 'Coffee / Tea' },
    { strCategory: 'Homemade Liqueur' },
    { strCategory: 'Punch / Party Drink' },
    { strCategory: 'Beer' },
    { strCategory: 'Soft Drink' },
  ],
};
// export const mockCorba = {
//   meals: [
//     {
//       idMeal: '52977',
//       strCategory: 'Side',
//       strMealThumb: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
//       strMeal: 'Corba',
//       strArea: 'Turkish',
//       strIngredient1: 'Lentils',
//       strIngredient2: 'Onion',
//       strIngredient3: 'Carrots',
//       strIngredient4: 'Tomato Puree',
//       strIngredient5: 'Cumin',
//       strIngredient6: 'Paprika',
//       strIngredient7: 'Mint',
//       strIngredient8: 'Thyme',
//       strIngredient9: 'Black Pepper',
//       strIngredient10: 'Red Pepper Flakes',
//       strIngredient11: 'Vegetable Stock',
//       strIngredient12: 'Water',
//       strIngredient13: 'Sea Salt',
//       strMeasure1: '1 cup ',
//       strMeasure2: '1 large',
//       strMeasure3: '1 large',
//       strMeasure4: '1 tbs',
//       strMeasure5: '2 tsp',
//       strMeasure6: '1 tsp ',
//       strMeasure7: '1/2 tsp',
//       strMeasure8: '1/2 tsp',
//       strMeasure9: '1/4 tsp',
//       strMeasure10: '1/4 tsp',
//       strMeasure11: '4 cups ',
//       strMeasure12: '1 cup ',
//       strMeasure13: 'Pinch',
//       strInstructions: 'Pick through your lentils for any foreign debris, rinse them 2 or 3 times, drain, and set aside.  Fair warning, this will probably turn your lentils into a solid block that you ll have to break up later',
//       strYoutube: 'https://www.youtube.com/watch?v=VVnZd8A84z4',
//     },
//   ],
// };
// export const mockSushi = {
//   meals: [
//     {
//       idMeal: '53065',
//       strCategory: 'Seafood',
//       strMealThumb: 'https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg',
//       strMeal: 'Sushi',
//       strArea: 'Japanese',
//       strIngredient1: 'Sushi Rice',
//       strIngredient2: 'Rice wine',
//       strIngredient3: 'Caster Sugar',
//       strIngredient4: 'Mayonnaise',
//       strIngredient5: 'Rice wine',
//       strIngredient6: 'Soy Sauce',
//       strIngredient7: 'Cucumber',
//       strMeasure1: '300ml ',
//       strMeasure2: '100ml',
//       strMeasure3: '2 tbs',
//       strMeasure4: '3 tbs',
//       strMeasure5: '1 tbs',
//       strMeasure6: '1 tbs',
//       strMeasure7: '1',
//       strInstructions: 'TO MAKE SUSHI ROLLS: Pat out some rice. Lay a nori sheet on the mat, shiny-side down. Dip your hands in the vinegared water, then pat handfuls of rice on top in a 1cm thick layer, leaving the furthest edge from you clear.',
//       strYoutube: 'https://www.youtube.com/watch?v=ub68OxEypaY',
//     },
//   ],
// };

// export const mockDataRecipesMeals = {
//   meals: [
//     {
//       idMeal: '52977',
//       strCategory: 'Side',
//       strMealThumb: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
//       strMeal: 'Corba',
//       strArea: 'Turkish',
//       strIngredient1: 'Lentils',
//       strIngredient2: 'Onion',
//       strIngredient3: 'Carrots',
//       strIngredient4: 'Tomato Puree',
//       strIngredient5: 'Cumin',
//       strIngredient6: 'Paprika',
//       strIngredient7: 'Mint',
//       strIngredient8: 'Thyme',
//       strIngredient9: 'Black Pepper',
//       strIngredient10: 'Red Pepper Flakes',
//       strIngredient11: 'Vegetable Stock',
//       strIngredient12: 'Water',
//       strIngredient13: 'Sea Salt',
//       strMeasure1: '1 cup ',
//       strMeasure2: '1 large',
//       strMeasure3: '1 large',
//       strMeasure4: '1 tbs',
//       strMeasure5: '2 tsp',
//       strMeasure6: '1 tsp ',
//       strMeasure7: '1/2 tsp',
//       strMeasure8: '1/2 tsp',
//       strMeasure9: '1/4 tsp',
//       strMeasure10: '1/4 tsp',
//       strMeasure11: '4 cups ',
//       strMeasure12: '1 cup ',
//       strMeasure13: 'Pinch',
//       strInstructions: 'Pick through your lentils for any foreign debris, rinse them 2 or 3 times, drain, and set aside.  Fair warning, this will probably turn your lentils into a solid block that you ll have to break up later',
//       strYoutube: 'https://www.youtube.com/watch?v=VVnZd8A84z4',
//     },
//     {
//       idMeal: '53065',
//       strCategory: 'Seafood',
//       strMealThumb: 'https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg',
//       strMeal: 'Sushi',
//       strArea: 'Japanese',
//       strIngredient1: 'Sushi Rice',
//       strIngredient2: 'Rice wine',
//       strIngredient3: 'Caster Sugar',
//       strIngredient4: 'Mayonnaise',
//       strIngredient5: 'Rice wine',
//       strIngredient6: 'Soy Sauce',
//       strIngredient7: 'Cucumber',
//       strMeasure1: '300ml ',
//       strMeasure2: '100ml',
//       strMeasure3: '2 tbs',
//       strMeasure4: '3 tbs',
//       strMeasure5: '1 tbs',
//       strMeasure6: '1 tbs',
//       strMeasure7: '1',
//       strInstructions: 'TO MAKE SUSHI ROLLS: Pat out some rice. Lay a nori sheet on the mat, shiny-side down. Dip your hands in the vinegared water, then pat handfuls of rice on top in a 1cm thick layer, leaving the furthest edge from you clear.',
//       strYoutube: 'https://www.youtube.com/watch?v=ub68OxEypaY',
//     },
//   ],
// };

// export const mockDataRecipesDrinks = {
//   drinks: [
//     {
//       idDrink: '17837',
//       strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg',
//       strDrink: 'Adam',
//       strCategory: 'Ordinary Drink',
//       strAlcoholic: 'Alcoholic',
//       strInstructions: 'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.',
//       strVideo: null,
//       strIngredient1: 'Dark rum',
//       strIngredient2: 'Lemon juice',
//       strIngredient3: 'Grenadine',
//       strMeasure1: '2 oz ',
//       strMeasure2: '1 oz ',
//       strMeasure3: '1 tsp ',
//     },
//     {
//       idDrink: '14610',
//       strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg',
//       strCategory: 'Shot',
//       strAlcoholic: 'Alcoholic',
//       strInstructions: 'Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.',
//       strVideo: null,
//       strIngredient1: '151 proof rum',
//       strIngredient2: 'Wild Turkey',
//       strMeasure1: '1 oz Bacardi ',
//       strMeasure2: '1 oz ',
//     },
//   ],
// };
